# Packages
library(mlogit)
library(plyr)
library(dplyr)
library(AER)
library(MASS)

Traindata <- read.csv("D:/CVEN/9407/TrainDataset.csv", header = TRUE, sep = ',')
head(Traindata)
Traindata$satisfaction <- "0"

for (i in 1:nrow(Traindata)){
  if (Traindata$losatlc[i] > 7) {
    Traindata$satisfaction[i] = 2
  } else {
    if (Traindata$losatlc[i] > 4) {
      Traindata$satisfaction[i] = 1
    }
  }
}

Traindata$original <- Traindata$losatlc
Traindata$losatlc <- NULL
colnames(Traindata)[ncol(Traindata)] <- "losatlc"
Traindata$waveid <- 1:nrow(Traindata)
Traindata <- na.omit(Traindata)

Traindata_dissatisfaction <- Traindata
Traindata_dissatisfaction$group <- "dissatisfaction"
Traindata_medium <- Traindata
Traindata_medium$group <- "medium"
Traindata_complete <- Traindata
Traindata_complete$group <- "complete"
Traindata <- rbind.data.frame(Traindata_complete, Traindata_medium, Traindata_dissatisfaction)
Traindata$choice <- "no"

for (i in 1:nrow(Traindata)){
  if (Traindata$satisfaction[i] == "0" & Traindata$group[i] == "dissatisfaction"){
    Traindata$choice[i] = "yes"
  }
  if (Traindata$satisfaction[i] == "1" & Traindata$group[i] == "medium"){
    Traindata$choice[i] = "yes"
  }
  if (Traindata$satisfaction[i] == "2" & Traindata$group[i] == "complete"){
    Traindata$choice[i] = "yes"
  }
}

Traindata <- Traindata %>% arrange(waveid, group)
Traindata <- as.data.frame(Traindata)
write.csv(Traindata, "D:/CVEN/9407/report3/TrainDataset_MNL.csv")

Traindata <- read.csv("D:/CVEN/9407/report3/TrainDataset_MNL.csv", sep = ",", header = TRUE)
head(Traindata)
Train_logit <- mlogit.data(Traindata, choice="choice", shape="long", alt.levels = c("complete", "dissatisfaction", "medium"),
                           chid.var="waveid", drop.index = TRUE)
head(Train_logit)

#Using variables from linear model
f_1 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + CoupleW + Le_fnw + hhad10_4 + hhec10_5)
model_1 <- mlogit(f_1, data=Train_logit, reflevel="complete")
summary(model_1)
AIC(model_1)

f_2 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + CoupleW + Le_fnw + hhad10_4)
model_2 <- mlogit(f_2, data=Train_logit, reflevel="complete")
summary(model_2)
AIC(model_2)

f_3 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + CoupleW + hhad10_4)
model_3 <- mlogit(f_3, data=Train_logit, reflevel="complete")
summary(model_3)
AIC(model_3)

f_4 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + CoupleW)
model_4 <- mlogit(f_4, data=Train_logit, reflevel="complete")
summary(model_4)
AIC(model_4)

f_5 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1)
model_5 <- mlogit(f_5, data=Train_logit, reflevel="complete")
summary(model_5)
AIC(model_5)

variable_list <- read.csv("D:\\CVEN\\9407\\variable_names_1.csv", sep = ',', header = TRUE)
variable_list <- na.omit(variable_list)
variable_list <- subset(variable_list, variable_list[1] != "lscom")
variable_list <- subset(variable_list, variable_list[1] != "lsvol")
variable_list <- subset(variable_list, variable_list[1] != "jbmsall")
variable_list <- subset(variable_list, variable_list[1] != "gh1")
variable_list <- subset(variable_list, variable_list[1] != "Renter")

AIC_value <- matrix(c(0), ncol = 1)
colnames(AIC_value) <- "AIC_value"

f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hh0_4)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hh5_9)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hh10_14)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hhadult)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hifdip)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hsrnti)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hsmgi)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hxyedci)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hxyhlpi)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hsvalui)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hsbedrm)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + tifdip)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hhfty)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + jbmmth)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hhyng)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hhold)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + jompf)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + lsemp)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + lshw)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + lsod)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + lschd)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + bmi)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + Female)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + Married)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + ESL)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + Le_mar)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + Le_sep)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + Le_job)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + Le_bth)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + Le_prg)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + Le_death)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + Le_fni)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + Le_fnw)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + Le_frd)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + Le_prm)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + Le_rtr)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + Le_ins)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + Mltpljob)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + Manager)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + Professional)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + Technician)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + ServiceWorker)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + Administrative)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + SalesWorker)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + MachineryOperator)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + Labour)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + FlxWork)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + HmWork)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + PrtStudy)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + FullStudy)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + Postgrad)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + Bachelor)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + CoupleWo)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + CoupleW)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + LoneW)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))
f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + Single)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_6))

AIC_value <- AIC_value[-1,]
loop_1 <- cbind.data.frame(variable_list, AIC_value)

f_6 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage)
model_6 <- mlogit(f_6, data=Train_logit, reflevel="complete")
summary(model_6)
AIC(model_6)

variable_list <- subset(variable_list, variable_list[1] != "hgage")

AIC_value <- matrix(c(0), ncol = 1)
colnames(AIC_value) <- "AIC_value"

f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh0_4)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh5_9)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hhadult)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hifdip)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hsrnti)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hsmgi)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hxyedci)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hxyhlpi)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hsvalui)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hsbedrm)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + tifdip)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hhfty)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + jbmmth)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hhyng)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hhold)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + jompf)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + lsemp)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + lshw)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + lsod)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + lschd)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + bmi)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + Female)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + Married)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + ESL)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + Le_mar)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + Le_sep)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + Le_job)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + Le_bth)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + Le_prg)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + Le_death)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + Le_fni)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + Le_fnw)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + Le_frd)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + Le_prm)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + Le_rtr)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + Le_ins)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + Mltpljob)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + Manager)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + Professional)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + Technician)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + ServiceWorker)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + Administrative)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + SalesWorker)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + MachineryOperator)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + Labour)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + FlxWork)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + HmWork)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + PrtStudy)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + FullStudy)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + Postgrad)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + Bachelor)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + CoupleWo)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + CoupleW)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + LoneW)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))
f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + Single)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_7))

AIC_value <- AIC_value[-1,]
loop_2 <- cbind.data.frame(variable_list, AIC_value)

f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + Le_fnw)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
summary(model_7)
AIC(model_7) #not significant

f_7 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14)
model_7 <- mlogit(f_7, data=Train_logit, reflevel="complete")
summary(model_7)
AIC(model_7)

variable_list <- subset.data.frame(variable_list, variable_list[1] != "hh10_14")

AIC_value <- matrix(c(0), ncol = 1)
colnames(AIC_value) <- "AIC_value"

f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hh0_4)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hh5_9)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhadult)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hifdip)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hsrnti)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hsmgi)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hxyedci)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hxyhlpi)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hsvalui)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hsbedrm)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + tifdip)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhfty)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + jbmmth)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhyng)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhold)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + jompf)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + lsemp)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + lshw)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + lsod)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + lschd)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + bmi)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + Female)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + Married)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + ESL)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + Le_mar)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + Le_sep)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + Le_job)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + Le_bth)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + Le_prg)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + Le_death)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + Le_fni)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + Le_fnw)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + Le_frd)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + Le_prm)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + Le_rtr)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + Le_ins)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + Mltpljob)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + Manager)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + Professional)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + Technician)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + ServiceWorker)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + Administrative)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + SalesWorker)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + MachineryOperator)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + Labour)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + FlxWork)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + HmWork)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + PrtStudy)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + FullStudy)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + Postgrad)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + Bachelor)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + CoupleWo)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + CoupleW)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + LoneW)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))
f_8 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + Single)
model_8 <- mlogit(f_8, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_8))

variable_list_2 <- read.csv("D:/CVEN/9407/variable_names_2.csv", header = TRUE, sep = ',')
AIC_value <- matrix(c(0), ncol = 1)
colnames(AIC_value) <- "AIC_value"

f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhad10_1)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhad10_2)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhad10_3)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhad10_4)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhad10_5)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhad10_6)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhad10_7)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhad10_8)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhad10_9)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhda10_1)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhda10_2)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhda10_3)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhda10_4)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhda10_5)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhda10_6)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhda10_7)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhda10_8)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhda10_9)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhec10_1)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhec10_2)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhec10_3)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhec10_4)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhec10_5)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhec10_6)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhec10_7)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhec10_8)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhec10_9)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhed10_1)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhed10_2)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhed10_3)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhed10_4)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhed10_5)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhed10_6)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhed10_7)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhed10_8)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))
f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhed10_9)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
AIC_value <- rbind.data.frame(AIC_value, AIC(model_9))

AIC_value <- AIC_value[-1,]
loop_4 <- cbind.data.frame(variable_list_2, AIC_value)

f_9 <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14 + hhda10_1)
model_9 <- mlogit(f_9, data=Train_logit, reflevel="complete")
summary(model_9)
AIC(model_9)

f_final <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14)
model_final <- mlogit(f_final, data=Train_logit, reflevel="complete")
f_final_test <- mFormula(choice ~ 0 | lscom + lsvol + Renter + hgage + hh10_14)
model_final_test <- mlogit(f_final_test, data=Train_logit, reflevel="complete")
hmftest(model_final, model_final_test, data = Train_logit)

summary(model_final)
AIC(model_final)
ci <- confint(model_final)
confint.default(model_final)
exp(coef(model_final))

testdata <- read.csv("D:/CVEN/9407/testDataset.csv", header = TRUE, sep = ',')
head(testdata)
testdata$satisfaction <- "0"

for (i in 1:nrow(testdata)){
  if (testdata$losatlc[i] > 7) {
    testdata$satisfaction[i] = 2
  } else {
    if (testdata$losatlc[i] > 4) {
      testdata$satisfaction[i] = 1
    }
  }
}

testdata$original <- testdata$losatlc
testdata$losatlc <- NULL
colnames(testdata)[ncol(testdata)] <- "losatlc"
testdata$waveid <- 1:nrow(testdata)
testdata <- na.omit(testdata)

testdata_dissatisfaction <- testdata
testdata_dissatisfaction$group <- "dissatisfaction"
testdata_medium <- testdata
testdata_medium$group <- "medium"
testdata_complete <- testdata
testdata_complete$group <- "complete"
testdata <- rbind.data.frame(testdata_complete, testdata_medium, testdata_dissatisfaction)
testdata$choice <- "no"

for (i in 1:nrow(testdata)){
  if (testdata$satisfaction[i] == "0" & testdata$group[i] == "dissatisfaction"){
    testdata$choice[i] = "yes"
  }
  if (testdata$satisfaction[i] == "1" & testdata$group[i] == "medium"){
    testdata$choice[i] = "yes"
  }
  if (testdata$satisfaction[i] == "2" & testdata$group[i] == "complete"){
    testdata$choice[i] = "yes"
  }
}

testdata <- testdata %>% arrange(waveid, group)
testdata <- as.data.frame(testdata)
write.csv(testdata, "D:/CVEN/9407/report3/testDataset_MNL.csv")

testdata <- read.csv("D:/CVEN/9407/report3/testDataset_MNL.csv", sep = ",", header = TRUE)
head(testdata)
test_logit <- mlogit.data(testdata, choice="choice", shape="long", alt.levels = c("complete", "dissatisfaction", "medium"),
                           chid.var="waveid", drop.index = TRUE)
head(test_logit)


f_final <- mFormula(choice ~ 0 | lscom + lsvol + jbmsall + Renter + gh1 + hgage + hh10_14)
model_final <- mlogit(f_final, data=Train_logit, reflevel="complete")
prediction <- predict(model_final, newdata = testdata)
head(prediction)

write.csv(prediction, "D:/CVEN/9407/report3/result_MNL.csv")

result <- read.csv("D:/CVEN/9407/report3/result_MNL.csv", header = TRUE, sep = ',')
head(result)
predict <- cbind.data.frame(testdata, result)
head(predict)
summary(predict$prediction)
table(predict$satisfaction)

